### ISSUE TITLE
EntryImageUrl error

### ISSUE THREAD

**Issue by Nick-Shannon** [snarfed/instagram-atom#7]
Hey snarfed, 

I've been using your fantastic Instagram-atom tool & IFTTT to send photos to Twitter.

Recently, the 'EntryImageUrl' has been throwing-up an error: Bad URL timestamp. 

Seems instagram has changed something.

**EntryImageUrl**
<a target="_blank" href="https://scontent-mia3-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/75214656_109030843768161_4449085355721986779_n.jpg?_nc_ht=scontent-mia3-1.cdninstagram.com&amp;_nc_cat=109&amp;oh=1243e5b3e7e5e03d6d90a146ba7bf3dd&amp;oe=5E79D867">https://scontent-mia3-1.cdninstagram.com/v/t51.2885-15/e35/p1080x1080/75214656_109030843768161_4449085355721986779_n.jpg?_nc_ht=scontent-mia3-1.cdninstagram.com&amp;_nc_cat=109&amp;oh=1243e5b3e7e5e03d6d90a146ba7bf3dd&amp;oe=5E79D867</a>

<img src="https://newzea1ander.files.wordpress.com/2019/12/annotation-2019-12-07-224016.png"
alt="IFTTT Instagram">

**Comment by snarfed** [comment]
hey nick, sorry for the trouble!

where are you seeing this problem? in your reader? or your IFTTT script? that example URL works ok if you replace the `&amp;`s with `&`s. they get escaped in the Atom feed because it's XML. they should still work ok in readers. as an example, i use NewsBlur, and they're showing up ok there right now.

**Comment by Nick-Shannon** [comment]
You're correct.  The issue is related to the `&amp;`  & the IFTTT applet.   I've seen the complaint elsewhere. 
I may follow-up with IFTTT... or just wait until they fix it.
